### ISSUE TITLE
Clone to specific host

### ISSUE THREAD

**Issue by reubenur-rahman** [sijis/pyvmomi-examples#4]
Hi,

I want to clone a template and relocate the VM on each host within a cluster. Now 

relocatespec = vim.vm.RelocateSpec()
relocatespec.host = host
relocatespec.pool = resource_pool

I don't have any resource pool in my setup so when I'm setting only host I am facing error that pool is a required parameter. If I give both host and pool then the code is always trying on one host only. 

Any idea how to resolve ?

Regards,
Reuben

**Comment by sijis** [comment]
I don't have a definitive answer as all my environments have a resource pool. Based on the [docs](http://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.wssdk.apiref.doc/index.html&single=true&__utma=207178772.1797969770.1400718506.1400718506.1400718506.1&__utmb=207178772.0.10.1400718506&__utmc=207178772&__utmx=-&__utmz=207178772.1400718506.1.1.utmcsr=google|utmccn=%28organic%29|utmcmd=organic|utmctr=%28not%20provided%29&__utmv=-&__utmk=174815265) it looks like if its a template to vm spec, its required.

If that pool is needed and you don't have one, try this snippet and see if you get a list of pools. There may be a default one you can use. Also as a wild guess, try None or "" as values.

``` python
pools = vmutils.get_resource_pools(si)
for p in pools:
    print p
```

Its just worth a shot.

**Comment by sijis** [comment]
Oh.. i just realized you mentioned host, not pool.

This may work

``` python
dest_host = vmutils.get_host_by_name(si, 'esx2')
...
relocatespec.host = dest_host
...
```

In my specific case, we have DRS setup, so it doesn't matter which host i select since DRS will pick a host for me when vm is powered on.

**Comment by GilGald** [comment]
I think you should not close this.
I have the same problem.
when I have 2 hosts and one is in maintenance mode it chooses the 1st host (which is in maintenance mode) and  when I try to add a hard coded host that I know for sure is not in maintenance it wont work.
relocatespec.host = dest_host 

is says :  the operation is not allowed in the current state of the host
