### ISSUE TITLE
Non OS-specific create_vm

### ISSUE THREAD

**Issue by mzenzie** [sijis/pyvmomi-examples#5]
Forgive my lack of knowledge of vsphere, but I've been poring over the docs for a while and still can't figure out what to change the LinuxPrep command to in order to make it work with windows VMs. Would I have to change anything else to make it work?

**Comment by sijis** [comment]
I cant say ive done any of it, however looking at the link below you can use sysprep and syspreptext.

You will probably have to change some of the configspec details as windows would be looking for slightly different parameters.

https://vdc-download.vmware.com/vmwb-repository/dcr/3d076a12-29a2-4d17-9269-cb8150b5a37f/8b5969e2-1a66-4425-af17-feff6d6f705d/SDK/sms-sdk/docs/ReferenceGuide/vim.vm.customization.IdentitySettings.html

**Comment by mzenzie** [comment]
Nevermind my earlier comment (the deleted one), I forgot that you can't name windows computers with lower-case letters.

**Comment by sijis** [comment]
OK. Are you good then?

**Comment by mzenzie** [comment]
I'm afraid not. I thought that I had fixed it, but when I get into setup (it starts up the template vm, then after a few minutes shuts down and runs startup to apply the settings), I get a "Windows could not parse or process the unattend answer file for pass [specialize]. The settings specified in the answer file cannot be applied. The error was detected while processing settings for component [MIcrosoft-Windows-Shell-Setup]."

From this, I believe that one of the names I supplied is invalid, though I'm having trouble figuring out which one. Currently, the code relevant to the failing part of sysprep looks like:

userData = vim.vm.customization.userData(
  fullName = settings.name # "MATT"
  orgName = settings.org  # "myorg"
  productId = "BVXBC-BW6K8-... etc." # A place holder key with correct syntax. Docs say it should be replaced by the key from the volume-licensed windows
  computerName = vim.vm.customization.FixedName(name = "PROTEUS"))

I've been struggling with this particular bug for a while and am not sure where I've gone wrong.

EDIT: Hate to say it, but I've found the problem again. It seems that even though the docs claim that productId is a necessary field, it can be omitted without stopping the setup. I can post my code modified to work with both windows and linux VMs if you would like.

**Comment by sijis** [comment]
If you still have that sample code and could share it, that would be great.

**Comment by mzenzie** [comment]
I'm unfortunately unable to share the actual code due to legal stuff, but it's not too complicated.

For windows, you have to create a big composite vim.vm.customization.Sysprep object with all the necessary fields, which you then use as the identity for the customization specification. The hierarchy of things you have to fill out is as follows:

vim.vm.customization.Sysprep

-vim.vm.customization.GuiUnattended (in the guiUnattended field)

-- autoLogon: True or False depending on whether you want the vm to automatically logon

-- autoLogonCount: the number of times to autologon

-- vim.vm.customization.password (in the password field)

--- value: The password to login with

--- plaintext: True or False depending on whether password is plaintext or not

-- timeZone: The code for the time zone of the computer. For example, EST is 35.

-vim.vm.customization.Identification (in the identification field, this object needs no attributes)

-vim.vm.customization.UserData (in the userData field)

--fullName: user's full name

--orgName: organization's name

--computerName: computer's name

These were all the fields I messed with, but you can find more [here](https://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.customization.Sysprep.html?resultof=%2522%2573%2579%2573%2570%2572%2565%2570%2522%2520).

**Comment by khalilnawar** [comment]
hi,
@sijis  please i have problem in create VM script : unresolved reference vim.vm .
how fix this problem please ?
