### ISSUE TITLE
use templeate clone windows, the vm machine created but ip not setted. 

### ISSUE THREAD

**Issue by hustcsxg** [sijis/pyvmomi-examples#8]
note: My new windows machine can mstsc after mannual config by me,just set ip.

#cloneSpec = vim.vm.CloneSpec(powerOn=True, template=False, location=relocateSpec, customization=customspec, config=vmconf)

why commend this line in demo file: create_vm? customspec cannot use?

**Comment by hustcsxg** [comment]
this guy has the same question [Question](https://stackoverflow.com/questions/30765940/how-do-i-modify-an-existing-vm-templates-only-ethernet-adapters-ip-address-wit/61317098#61317098)
but four years no answer!!!

**Comment by sijis** [comment]
I know my examples worked for Linux based vms.

I haven't touched or used this code in years, so it's possible the api has changed and now things are different.

**Comment by hustcsxg** [comment]
> I know my examples worked for Linux based vms.
> 
> I haven't touched or used this code in years, so it's possible the api has changed and now things are different.

thanks reply, i fond method to solve this ,CustomizeGuest_Task required version vSphere API 6.8.7
